# Generated by Django 5.1.7 on 2025-03-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userquizresult_options_quiz_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquizresult',
            unique_together=set(),
        ),
    ]
