# Generated by Django 5.1.7 on 2025-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quiz_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image_source',
            field=models.CharField(blank=True, choices=[('UPLOAD', 'Upload'), ('PEXELS', 'Pexels'), ('UNSPLASH', 'Unsplash')], max_length=20, null=True),
        ),
    ]
