# Generated by Django 5.1.7 on 2025-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quiz_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_source',
            field=models.CharField(blank=True, choices=[('UPLOAD', 'Upload'), ('PEXELSORUNSPLASH', 'Pexels or Unsplash')], max_length=20, null=True),
        ),
    ]
