# Generated by Django 5.1.7 on 2025-03-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_quiz_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image_source',
        ),
    ]
