# Generated by Django 5.1.7 on 2025-03-26 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_message_options_message_read_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
