# Generated by Django 5.1.7 on 2025-04-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_message_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
