# Generated by Django 5.1.7 on 2025-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quiz_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
